---
name: Bug Report
about: דיווח על באג בתהליך או בעיצוב
title: "[Bug] "
labels: bug
assignees: ''

---

## 🐛 תיאור הבאג

תיאור קצר וברור של הבאג.

## 🔄 איך לשחזר

שלבים לשחזר:
1. גש ל-'...'
2. לחץ על '...'
3. גלול למטה ל-'...'
4. ראה את השגיאה

## ✅ התנהגות צפויה

מה הייתה צריכה להיות ההתנהגות?

## ❌ התנהגות בפועל

מה קרה בפועל?

## 📸 Screenshots

אם רלוונטי, הוסף screenshots.

## 💻 סביבה

- דפדפן: [Firefox / Chrome / Safari / ...]
- גודל מסך: [Desktop 1920x1080 / Mobile 375x667 / ...]
- OS: [MacOS / Windows / Linux / iOS / Android]

## 📝 מידע נוסף

הוסף כל מידע נוסף רלוונטי כאן.

